# Generated by Django 4.0.5 on 2022-06-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0003_alter_neighbourhood_health_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='authority_center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='authority_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='health_center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='health_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
