# Generated by Django 4.0.5 on 2022-06-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0007_alter_business_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
