# Generated by Django 4.0.5 on 2022-06-19 11:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0009_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='info',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
