# Generated by Django 4.0.5 on 2022-06-19 18:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0010_alter_post_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='image',
            field=cloudinary.models.CloudinaryField(default='image', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
